name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
        example: [examples/example1/example1.c, examples/example2/example2.c]
        special-example: [examples/example2/example2.c]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Run PlatformIO CI UNO
        run: pio ci --lib="." --board=uno
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.example }}
          PLATFORMIO_BUILD_FLAGS: -D BOARD_UNO
      
      - name: Run PlatformIO CI BLUEPILL
        run: pio ci --lib="." --board=bluepill_f103c8
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.example }}
          PLATFORMIO_BUILD_FLAGS: -D BOARD_BLUEPILL
      
      # - name: Run PlatformIO CI LCD
      #   run: pio ci --lib="." --project-option="lib_deps=marcoschwartz/LiquidCrystal_I2C@^1.1.4" --board=uno --board=bluepill_f103c8
      #   env:
      #     PLATFORMIO_CI_SRC: ${{matrix.special-example}}
